export const footerLinks = [
  {
    heading: 'POPULAR CATEGORIES',
    links: ['Cars', 'Flats for rent', 'Jobs', 'Mobile Phones'],
  },
  {
    heading: 'TRENDING SEARCHES',
    links: ['Bikes', 'Watches', 'Books', 'Dogs'],
  },
  {
    heading: 'ABOUT US',
    links: ['About OLX Group', 'OLX Blog', 'Contact Us', 'OLX for Businesses'],
  },
  {
    heading: 'OLX',
    links: ['Help', 'Sitemap', 'Legal & Privacy Information'],
  },
];

export const categories = [
  [
    {
      title: 'Vehicles',
      links: [
        'Tractors & Trailers',
        'Boats',
        'Other Vehicles',
        'Rickshaw & Chingchi',
        'Buses, Vans & Trucks',
        'Spare Parts',
        'Cars Accessories',
        'Cars on Installments',
        'Cars',
      ],
    },
    {
      title: 'Mobiles',
      links: ['Mobile Phones', 'Accessories', 'Tablets'],
    },
    {
      title: 'Electronics & Home Appliances',
      links: [
        'Washing Machines & Dryers',
        'Fridges & Freezers',
        'AC & Coolers',
        'Kitchen Appliances',
        'Generators, UPS & Power Solutions',
        'Other Home Appliances',
        'Games & Entertainment',
        'Cameras & Accessories',
        'TV - Video - Audio',
        'Computers & Accessories',
      ],
    },
    {
      title: 'Property for Sale',
      links: [
        'Portions & Floors',
        'Shops - Offices - Commercial Space',
        'Apartments & Flats',
        'Houses',
        'Land & Plots',
      ],
    },
  ],
  [
    {
      title: 'Animals',
      links: [
        'Other Animals',
        'Pet Food & Accessories',
        'Horses',
        'Livestock',
        'Dogs',
        'Cats',
        'Hens & Aseel',
        'Birds',
        'Fish & Aquariums',
      ],
    },
    {
      title: 'Furniture & Home Decor',
      links: [
        'Other Household Items',
        'Office Furniture',
        'Curtains & Blinds',
        'Rugs & Carpets',
        'Painting & Mirrors',
        'Garden & Outdoor',
        'Tables & Dining',
        'Home Decoration',
        'Beds & Wardrobes',
        'Sofa & Chairs',
      ],
    },
    {
      title: 'Business, Industrial & Agriculture',
      links: [
        'Medical & Pharma',
        'Other Business & Industry',
        'Agriculture',
        'Construction & Heavy Machinery',
        'Trade & Industrial',
        'Food & Restaurants',
        'Business for Sale',
      ],
    },
    {
      title: 'Bikes',
      links: ['Scooters', 'ATV & Quads', 'Bicycles', 'Spare Parts', 'Motorcycles'],
    },
  ],
  [
    {
      title: 'Fashion & Beauty',
      links: [
        'Other Fashion',
        'Couture',
        'Lawn & Pret',
        'Wedding',
        'Watches',
        'Skin & Hair',
        'Make Up',
        'Jewellery',
        'Footwear',
        'Clothes',
        'Accessories',
      ],
    },
    {
      title: 'Property for Rent',
      links: [
        'Land & Plots',
        'Vacation Rentals - Guest Houses',
        'Roommates & Paying Guests',
        'Rooms',
        'Shops - Offices - Commercial Space',
        'Portions & Floors',
        'Apartments & Flats',
        'Houses',
      ],
    },
    {
      title: 'Jobs',
      links: [
        'Other Jobs',
        'Part - Time',
        'Domestic Staff',
        'Medical',
        'Manufacturing',
        'Accounting & Finance',
        'Human Resources',
        'Hotels & Tourism',
        'IT & Networking',
        'Sales',
        'Customer Service',
        'Education',
        'Advertising & PR',
        'Marketing',
        'Online',
      ],
    },
  ],
  [
    {
      title: 'Services',
      links: [
        'Farm & Fresh Food',
        'Catering & Restaurant',
        'Home & Office Repair',
        'Movers & Packers',
        'Maids & Domestic Help',
        'Health & Beauty',
        'Event Services',
        'Electronics & Computer Repair',
        'Other Services',
        'Web Development',
        'Drivers & Taxi',
        'Car Rental',
        'Travel & Visa',
        'Education & Classes',
      ],
    },
    {
      title: 'Books, Sports & Hobbies',
      links: ['Other Hobbies', 'Gym & Fitness', 'Sports Equipment', 'Musical Instruments', 'Books & Magazines'],
    },
    {
      title: 'Kids',
      links: ['Kids Accessories', 'Kids Bikes', 'Swings & Slides', 'Prams & Walkers', 'Toys', 'Kids Furniture'],
    },
  ],
];
